sudo: required

language: go

go:
  - master

before_install:
  - sudo apt-get -qq update && sudo apt-get install -y gcc clang make
  - wget -qO- https://github.com/P-H-C/phc-winner-argon2/archive/20171227.tar.gz | tar -xvz -C $HOME/. && ( cd $HOME/phc-winner-argon2-20171227/. && make && sudo make install )
  - ( cd /usr/lib/. && sudo ln -s libargon2.so libargon2.so.0 )

script:
  - go test -v -race -covermode=atomic -coverprofile=coverage.txt ./...

after_success:
  - bash <(curl -s https://codecov.io/bash)