sudo: required

language: go

go:
  - master

before_install:
  - go get github.com/mattn/goveralls
  - wget -qO- https://github.com/P-H-C/phc-winner-argon2/archive/20161029.tar.gz | tar -xvz -C $HOME/. && cd $HOME/phc-winner-argon2-20161029/.
  - sudo apt-get -qq update
  - sudo apt-get install -y gcc clang make
  - make && sudo make install
  - cd /usr/lib/.
  - sudo ln -s libargon2.so libargon2.so.0
  - cd $TRAVIS_BUILD_DIR

script:
  - $HOME/gopath/bin/goveralls -service=travis-ci
